checkoutLocation: go/src/github.com/whitaker-io/machine
workspaceLocation: go/src/github.com/whitaker-io/machine
image:
  file: .devcontainer/Dockerfile
tasks:
  - init: 
      go mod vendor
ports:
  - port: 5000
    onOpen: ignore
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true