// Code generated by 'yaegi extract github.com/whitaker-io/machine'. DO NOT EDIT.

package machine

import (
	"context"
	"reflect"
)

var symbols = map[string]map[string]reflect.Value{}

func init() {
	symbols["github.com/whitaker-io/machine"] = map[string]reflect.Value{
		// type definitions
		"Data":         reflect.ValueOf((*Data)(nil)),
		"Packet":       reflect.ValueOf((*Packet)(nil)),
		"Subscription": reflect.ValueOf((*Subscription)(nil)),
		"Applicative":  reflect.ValueOf((*Applicative)(nil)),
		"Retriever":    reflect.ValueOf((*Retriever)(nil)),
		"Fold":         reflect.ValueOf((*Fold)(nil)),
		"Fork":         reflect.ValueOf((*Fork)(nil)),
		"Sender":       reflect.ValueOf((*Sender)(nil)),

		// interface wrapper definitions
		"_Subscription": reflect.ValueOf((*_github_com_whitaker_io_machine_Subscription)(nil)),
	}
}

// _github_com_whitaker_io_machine_Subscription is an interface wrapper for Subscription type
type _github_com_whitaker_io_machine_Subscription struct {
	WClose func() error
	WRead  func(ctx context.Context) []Data
}

func (W _github_com_whitaker_io_machine_Subscription) Close() error { return W.WClose() }
func (W _github_com_whitaker_io_machine_Subscription) Read(ctx context.Context) []Data {
	return W.WRead(ctx)
}
